import { dev } from '$app/environment'

export const title = 'Blog'
export const description = 'My personal blog'
export const url = dev ? 'http://localhost:5173/' : 'url'
export const twitterUrl = ''
export const youtubeUrl = 'https://www.youtube.com/watch?v=1jjazON9cog'
export const githubUrl = 'https://github.com/shawndones/'
export const linkedinUrl = 'https://www.linkedin.com/in/shawndones'
export const email = 'shawndones@gmail.com'
// export const facebookUrl = ''
export const instagramUrl = 'https://www.instagram.com/savagetradition/'