import { dev } from '$app/environment'

export const title = 'Blog'
export const description = 'My personal blog'
export const url = dev ? 'http://localhost:5173/' : 'url'
export const twitterUrl = ''
export const youtubeUrl = ''
export const githubUrl = ''
export const linkedinUrl = ''
export const email = ''
export const facebookUrl = ''
